unstable_features = true # for "ignore", remove asap

ignore = [
    "benches/bench_rustfft.rs", 
    "benches/bench_rustfft_sse.rs",
    "benches/bench_rustfft_neon.rs", 
    "src/sse/sse_prime_butterflies.rs", 
    "src/neon/neon_prime_butterflies.rs",
    "benches/bench_compare_scalar_neon.rs",
    ]

